name: Deploy app service

on:
  workflow_call:
    inputs:
      workspace-name:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"

      - name: Make the azure function app artifact
        id: make-app-service-artifact
        run: |
          cd apps/app_service
          yarn install --immutable
          yarn build
          zip -r ${{ inputs.workspace-name }}.zip .
          echo "artifact-path=$(realpath ${{ inputs.workspace-name }}.zip)" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Upload workspace artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.workspace-name }}
          path: ${{ steps.make-app-service-artifact.outputs.artifact-path }}

  deploy:
    name: Deploy
    if: ${{ !github.event.act }}
    needs: [build]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download workspace artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.workspace-name }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to prod slot
        uses: azure/webapps-deploy@v2
        with:
          resource-group-name: io-d-itn-tracing-poc-rg
          app-name: io-d-itn-tracing-poc-app
          package: ${{ inputs.workspace-name }}.zip