name: Deploy

on:
  workflow_dispatch:
    inputs:
      workspace-name:
        type: string
        required: true

jobs:
  deploy_workspace_to_azure:
    name: Deploy
    uses: ./.github/workflows/function_deploy.yaml
    with:
      environment: dev
      workspace-name: ${{inputs.workspace-name}}
    secrets: inherit