name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy_workspace_to_azure:
    name: Deploy
    uses: ./.github/workflows/function_deploy.yaml
    with:
      environment: dev
      workspace-name: ./function_app
    secrets: inherit